### ISSUE TITLE
crashes on macOS with iced

### ISSUE THREAD

**Issue by fenhl** [PolyMeilex/rfd#3]
I tried to use `AsyncFileDialog` in an [iced](https://docs.rs/iced) app on macOS, but when trying to use the dialog, the app crashes, printing:

```
fatal runtime error: Rust cannot catch foreign exceptions
```

This happens on 0.1.2 as well as master.

**Comment by PolyMeilex** [comment]
That's probably something threading related, I'll see what can be done in this regard.

Some questions: 
1. Does it crash on creation or later?
2. If it crashes right away, on which tread does it happen? Like... On which thread `pick_file" fn is called?

**Comment by PolyMeilex** [comment]
Is this how you use it in `iced`?
```rust
fn update(&mut self, message: Message) -> Command<Message> {
    match message {
        Message::Open(_) => {
            return Command::perform(
                rfd::AsyncFileDialog::new().pick_file(),
                |ret| Message::Res(ret.map(|f| f.path().into())),
            );
        }
        Message::Res(path) => {
            println!("{:?}", path);
        }
    };
    Command::none()
}
```

And one more question:
Kinda related to previous question, when does the dialogue crashes? Does the dialogue open at all? Does it crash after selecting a file? After closing? etc.
If it crashes after close then I probably know what's the problem, otherwise it will be quite tricky one to figure out.

**Comment by fenhl** [comment]
Here's a minimal example, with the async code being called from a regular `Command`, as is the usual case in iced apps.

Cargo.toml:

```toml
[package]
name = "rfd-crash-example"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies.iced]
git = "https://github.com/hecrj/iced"
rev = "12c0c18d662d2b817b559b94c71d18e122c76990"

[dependencies.rfd]
git = "https://github.com/PolyMeilex/rfd"
rev = "ee4e55f8d2cb0a307cea650a05deaf9d4aa142fc"
```

main.rs:

```rust
use iced::{
    Application,
    Command,
    Element,
    Settings,
    widget::{
        Text,
        button::{
            self,
            Button,
        },
    },
};

#[derive(Debug, Clone)]
enum Message {
    Click,
    Nop,
}

#[derive(Default)]
struct App {
    btn: button::State,
}

impl Application for App {
    type Executor = iced::executor::Default;
    type Message = Message;
    type Flags = ();

    fn new((): ()) -> (App, Command<Message>) { (App::default(), Command::none()) }
    fn title(&self) -> String { format!("rfd crash example") }

    fn update(&mut self, msg: Message) -> Command<Message> {
        match msg {
            Message::Click => async {
                let dialog = rfd::AsyncFileDialog::new();
                println!("{:?}", std::thread::current().id());
                let _ = dialog.pick_file().await;
                Message::Nop
            }.into(),
            Message::Nop => Command::none(),
        }
    }

    fn view(&mut self) -> Element<'_, Message> {
        Button::new(&mut self.btn, Text::new("Pick File"))
            .on_press(Message::Click)
            .into()
    }
}

fn main() -> iced::Result {
    App::run(Settings::default())
}
```

The file dialog window never appears, and the output is:

```
ThreadId(6)
fatal runtime error: Rust cannot catch foreign exceptions
```

So the crash happens in `pick_file`, not `new`.
